version: "3"
services:
    postgres-db:
        image: postgres
        container_name: postgres-db
        restart: always
        ports:
            - "1234:5432"
        env_file:
            - ./apps/api/.env
        volumes:
            - volume_postgres_db:/var/lib/postgresql/data

    mongo-db:
        image: mongo
        container_name: mongo-db
        restart: always
        ports:
            - "27017:27017"
        env_file: ./apps/api/.env
        volumes:
            - volume_mongo_db:/data/db

    inovia-project-api:
        container_name: inovia-project-api
        build: ./apps/api
        ports:
            - 5000:5000
        depends_on:
            - postgres-db
            - mongo-db
        env_file:
            - ./apps/api/.env

    inovia-project-client:
        container_name: inovia-project-client
        build: ./apps/client
        volumes:
            - build_react:/var/www/html
        depends_on:
            - inovia-project-api

    nginx:
        container_name: nginx
        build: ./nginx
        ports:
            - 8080:80
        volumes:
            - build_react:/var/www/html
        depends_on:
            - inovia-project-api
            - inovia-project-client

volumes:
    volume_postgres_db:
    build_react:
    volume_mongo_db:
